/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.zbytes.demo.interfaces.rest;

import io.github.zbytes.demo.interfaces.rest.dto.User;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-11-29T10:28:17.922+05:45[Asia/Kathmandu]")

@Api(value = "User", description = "the User API")
public interface UserApi {

    /**
     * POST /users : Created user
     * This can only be done by the logged in user.
     *
     * @param user Created user object (required)
     * @return OK (status code 200)
     *         or Invalid user supplied (status code 400)
     */
    @ApiOperation(value = "Created user", nickname = "createUser", notes = "This can only be done by the logged in user.", authorizations = {
        @Authorization(value = "main_auth", scopes = {
            @AuthorizationScope(scope = "write:users", description = "modify or remove users")
            })
    }, tags={ "User", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 400, message = "Invalid user supplied") })
    @RequestMapping(value = "/users",
        consumes = "application/json",
        method = RequestMethod.POST)
    Mono<ResponseEntity<Void>> createUser(@ApiParam(value = "Created user object" ,required=true )   @RequestBody Mono<User> user, ServerWebExchange exchange);


    /**
     * DELETE /users/{username} : Deleted user
     * This can only be done by the logged in user.
     *
     * @param username The name that needs to be deleted (required)
     * @return OK (status code 200)
     *         or User not found (status code 404)
     */
    @ApiOperation(value = "Deleted user", nickname = "deleteUser", notes = "This can only be done by the logged in user.", authorizations = {
        @Authorization(value = "main_auth", scopes = {
            @AuthorizationScope(scope = "write:users", description = "modify or remove users")
            })
    }, tags={ "User", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 404, message = "User not found") })
    @RequestMapping(value = "/users/{username}",
        method = RequestMethod.DELETE)
    Mono<ResponseEntity<Void>> deleteUser(@ApiParam(value = "The name that needs to be deleted",required=true) @PathVariable("username") String username, ServerWebExchange exchange);


    /**
     * GET /users/{username} : Get user by user name
     * Some description of the operation. You can use &#x60;markdown&#x60; here. 
     *
     * @param username The name that needs to be fetched (required)
     * @param withEmail Filter users without email (optional)
     * @return Success (status code 200)
     *         or Forbidden (status code 403)
     *         or User not found (status code 404)
     */
    @ApiOperation(value = "Get user by user name", nickname = "getUserByName", notes = "Some description of the operation. You can use `markdown` here. ", response = User.class, authorizations = {
        @Authorization(value = "api_key"),
        @Authorization(value = "main_auth", scopes = {
            @AuthorizationScope(scope = "read:users", description = "read users info")
            })
    }, tags={ "User", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = User.class),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "User not found") })
    @RequestMapping(value = "/users/{username}",
        produces = "application/json", 
        method = RequestMethod.GET)
    Mono<ResponseEntity<User>> getUserByName(@ApiParam(value = "The name that needs to be fetched",required=true) @PathVariable("username") String username,@ApiParam(value = "Filter users without email")  @RequestParam(value = "with_email", required = false) Boolean withEmail, ServerWebExchange exchange);


    /**
     * GET /users : Get users
     * Some description of the operation. You can use &#x60;markdown&#x60; here. 
     *
     * @param page The page that needs to be fetched (required)
     * @param size The size that needs to be fetched (required)
     * @param sort The sort that needs to be fetched (optional)
     * @return Success (status code 200)
     *         or Forbidden (status code 403)
     */
    @ApiOperation(value = "Get users", nickname = "getUsers", notes = "Some description of the operation. You can use `markdown` here. ", response = User.class, responseContainer = "List", authorizations = {
        @Authorization(value = "api_key"),
        @Authorization(value = "main_auth", scopes = {
            @AuthorizationScope(scope = "read:users", description = "read users info")
            })
    }, tags={ "User", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = User.class, responseContainer = "List"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/users",
        produces = "application/json", 
        method = RequestMethod.GET)
    Mono<ResponseEntity<Flux<User>>> getUsers(@ApiParam(value = "The page that needs to be fetched", required = true)  @RequestParam(value = "page", required = true) Integer page,@ApiParam(value = "The size that needs to be fetched", required = true)  @RequestParam(value = "size", required = true) Integer size,@ApiParam(value = "The sort that needs to be fetched")  @RequestParam(value = "sort", required = false) String sort, ServerWebExchange exchange);


    /**
     * PUT /users/{username} : Updated user
     * This can only be done by the logged in user.
     *
     * @param user Updated user object (required)
     * @param username The name that needs to be updated (required)
     * @return OK (status code 200)
     *         or Invalid user supplied (status code 400)
     *         or Forbidden (status code 403)
     *         or User not found (status code 404)
     */
    @ApiOperation(value = "Updated user", nickname = "updateUser", notes = "This can only be done by the logged in user.", authorizations = {
        @Authorization(value = "main_auth", scopes = {
            @AuthorizationScope(scope = "write:users", description = "modify or remove users")
            })
    }, tags={ "User", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 400, message = "Invalid user supplied"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "User not found") })
    @RequestMapping(value = "/users/{username}",
        consumes = "application/json",
        method = RequestMethod.PUT)
    Mono<ResponseEntity<Void>> updateUser(@ApiParam(value = "Updated user object" ,required=true )   @RequestBody Mono<User> user,@ApiParam(value = "The name that needs to be updated",required=true) @PathVariable("username") String username, ServerWebExchange exchange);

}
